---
# tasks file for adguard

- name: Get DNS entries
  ansible.builtin.uri:
    url: "http://{{ adguard_host }}/control/rewrite/list"
    method: GET
    headers:
      Authorization: "Basic {{ adguard_auth }}"
    force_basic_auth: true
  register: result

- name: Add DNS entries
  ansible.builtin.uri:
    url: "http://{{ adguard_host }}/control/rewrite/add"
    method: POST
    headers:
      Authorization: "Basic {{ adguard_auth }}"
    force_basic_auth: true
    body_format: json
    body:
      domain: "{{ item }}"
      answer: "{{ machine_ip }}"
  with_items:
    - "{{ cluster_name }}.{{ base_domain }}"
    - "api.{{ cluster_name }}.{{ base_domain }}"
    - "api-int.{{ cluster_name }}.{{ base_domain }}"
    - "*.apps.{{ cluster_name }}.{{ base_domain }}"
  vars:
    query: "[?domain=='{{ item }}']|[?answer=='{{ machine_ip }}']"
  when: not result.json | community.general.json_query(query)
