---
- name: Install Single Node OpenShift Cluster on libvirt
  hosts: localhost
  connection: local

  vars_files:
    - sno_vars.yaml

  roles:
    - adguard
    - { role: haproxy, become: true }
    - { role: libvirt, become: true }
    - sno
    - { role: lvm, become: true }
